# Generated by Django 3.0.7 on 2021-06-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fundData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundcode', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('jzrq', models.CharField(max_length=18)),
                ('sjjz', models.FloatField(max_length=20)),
                ('zxjz', models.FloatField(max_length=20)),
                ('zxzf', models.FloatField(max_length=20)),
                ('gztime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='fundList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='admin', max_length=10)),
                ('fundcode', models.CharField(max_length=10)),
            ],
        ),
    ]
