# Generated by Django 3.0.7 on 2021-06-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundPlan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funddata',
            name='gztime',
            field=models.CharField(max_length=30),
        ),
    ]
