# Generated by Django 3.0.7 on 2021-07-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundPlan', '0003_funddata_pjzf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funddata',
            name='pjzf',
            field=models.FloatField(default=0, max_length=20),
        ),
    ]
