# Generated by Django 3.0.7 on 2021-07-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundPlan', '0005_funddata_jrzf'),
    ]

    operations = [
        migrations.CreateModel(
            name='fundtipslog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='admin', max_length=10)),
                ('fundcode', models.CharField(max_length=10)),
                ('jjzf', models.FloatField(default=0, max_length=20)),
                ('warehousetype', models.IntegerField(max_length=10)),
            ],
        ),
    ]
