# Generated by Django 3.0.7 on 2021-07-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundPlan', '0006_fundtipslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funddata',
            name='jzrq',
            field=models.DateTimeField(max_length=18),
        ),
    ]
