# Generated by Django 3.0.7 on 2021-07-15 11:20

from django.db import migrations, models
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ('fundPlan', '0009_funddata_jdzjrzf'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundlist',
            name='buytime',
            field=models.DateTimeField(default='2020-01-01', max_length=18),
        ),
        migrations.AddField(
            model_name='fundlist',
            name='isbuy',
            field=models.IntegerField(null=django.db.models.query.FlatValuesListIterable),
            preserve_default=django.db.models.query.FlatValuesListIterable,
        ),
        migrations.AlterField(
            model_name='fundtipslog',
            name='warehousetype',
            field=models.IntegerField(),
        ),
    ]
