# Generated by Django 2.1 on 2021-07-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundPlan', '0010_auto_20210715_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundlist',
            name='fundPosition',
            field=models.FloatField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='fundlist',
            name='fundprofitrate',
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='fundlist',
            name='selltime',
            field=models.DateTimeField(default='2040-01-01', max_length=18),
        ),
        migrations.AlterField(
            model_name='fundlist',
            name='buytime',
            field=models.DateTimeField(default='2040-01-01', max_length=18),
        ),
    ]
